#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: how-he-loves-bot

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
stage: dev
region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  tweet:
    handler: bot.tweet
    description: HowHeLoves Tweet function
    events:
      - schedule:
        name: Daily Tweet
        description: Tweet "Jesus Loves You every 24 hours"
        rate: cron(0 10 * * ? *)
